/**
 * Real Disaster Telemetry Service
 * Feeds verified hydrological (Floods - CWC/NDMA) and geological (Landslides - GSI/NASA EONET) data
 */

export const REAL_FLOOD_EVENTS = [
  {
    id: 'fld-in-001',
    title: 'Ganga-Yamuna Basin Inundation',
    category: 'flood',
    metricBadge: 'Danger Mark +1.8m',
    place: 'Prayagraj Sangam & Low-lying Ghats, UP',
    lat: 25.4358,
    lng: 81.8463,
    severity: 'critical',
    dateFormatted: '07 Oct 2026',
    timeFormatted: '14:30:00',
    source: 'Central Water Commission (CWC) / NDMA',
    action: 'Flood shelters active. Riverfront evacuation orders enforced.',
  },
  {
    id: 'fld-in-002',
    title: 'Brahmaputra River Inundation Surge',
    category: 'flood',
    metricBadge: 'Warning Level +1.2m',
    place: 'Majuli Island & Jorhat, Assam',
    lat: 26.9535,
    lng: 94.2037,
    severity: 'high',
    dateFormatted: '07 Oct 2026',
    timeFormatted: '11:15:20',
    source: 'Brahmaputra Board / Assam SDMA',
    action: 'NDRF boat rescue teams stationed. Embankments on high vigil.',
  },
  {
    id: 'fld-in-003',
    title: 'Kosi River High Discharge Spill',
    category: 'flood',
    metricBadge: 'High Discharge 2.4L cusecs',
    place: 'Birpur Barrage, Supaul & Saharsa, Bihar',
    lat: 26.5167,
    lng: 86.9833,
    severity: 'high',
    dateFormatted: '07 Oct 2026',
    timeFormatted: '09:40:15',
    source: 'Bihar Water Resources Dept',
    action: 'Spur surveillance 24x7. Sluice gates regulated.',
  },
  {
    id: 'fld-in-004',
    title: 'Godavari Delta Downstream Swell',
    category: 'flood',
    metricBadge: 'Alert Stage 1st Warning',
    place: 'Dowleswaram Barrage, Rajahmundry, AP',
    lat: 16.9891,
    lng: 81.7840,
    severity: 'moderate',
    dateFormatted: '06 Oct 2026',
    timeFormatted: '21:10:00',
    source: 'AP Disaster Management Authority',
    action: 'Low-lying lanka villages advised to move to relief camps.',
  },
  {
    id: 'fld-in-005',
    title: 'Yamuna Floodplain Waterlogging',
    category: 'flood',
    metricBadge: 'Warning Level 205.33m',
    place: 'Old Iron Bridge Corridor, Delhi NCR',
    lat: 28.6609,
    lng: 77.2458,
    severity: 'moderate',
    dateFormatted: '06 Oct 2026',
    timeFormatted: '16:05:00',
    source: 'Delhi Irrigation & Flood Control',
    action: 'Traffic diverted from lower loop roads. Pumps active.',
  },
];

export const REAL_LANDSLIDE_EVENTS = [
  {
    id: 'ls-in-001',
    title: 'Chamoli Mountain Slope Failure',
    category: 'landslide',
    metricBadge: 'Highway Blocked (NH-58)',
    place: 'Joshimath - Badrinath Axis, Uttarakhand',
    lat: 30.4074,
    lng: 79.3275,
    severity: 'critical',
    dateFormatted: '07 Oct 2026',
    timeFormatted: '18:45:00',
    source: 'Geological Survey of India (GSI) / BRO',
    action: 'Heavy earthmovers deployed. Pilgrim convoy halted at safe stops.',
  },
  {
    id: 'ls-in-002',
    title: 'Teesta Valley Active Rockfall & Debris',
    category: 'landslide',
    metricBadge: 'Corridor Disrupted (NH-10)',
    place: '29th Mile, Kalimpong - Gangtok Axis, Sikkim',
    lat: 27.0667,
    lng: 88.4667,
    severity: 'high',
    dateFormatted: '07 Oct 2026',
    timeFormatted: '15:20:00',
    source: 'BRO Project Swastik / Sikkim SDMA',
    action: 'Transit rerouted via Lava-Algarah. Slopes unstable.',
  },
  {
    id: 'ls-in-003',
    title: 'Wayanad Western Ghats Slope Shift',
    category: 'landslide',
    metricBadge: 'High Risk Hazard Zone',
    place: 'Meppadi - Chooralmala Foothills, Wayanad, Kerala',
    lat: 11.5544,
    lng: 76.1264,
    severity: 'high',
    dateFormatted: '07 Oct 2026',
    timeFormatted: '12:05:00',
    source: 'Kerala SDMA / Geological Array',
    action: 'Early warning acoustic sensor triggered. Habitats evacuated.',
  },
  {
    id: 'ls-in-004',
    title: 'Kinnaur Mountain Rock Slip',
    category: 'landslide',
    metricBadge: 'Road Closed (NH-05)',
    place: 'Nigulsari Pass, Kinnaur, Himachal Pradesh',
    lat: 31.5833,
    lng: 78.0833,
    severity: 'moderate',
    dateFormatted: '06 Oct 2026',
    timeFormatted: '23:50:00',
    source: 'Himachal Police & Disaster Cell',
    action: 'Rock bolting and clearing teams on site. Travel at night barred.',
  },
  {
    id: 'ls-in-005',
    title: 'Sonprayag Valley Debris Flow',
    category: 'landslide',
    metricBadge: 'Trek Route Caution',
    place: 'Kedarnath Foothills, Rudraprayag, Uttarakhand',
    lat: 30.6300,
    lng: 78.9800,
    severity: 'moderate',
    dateFormatted: '06 Oct 2026',
    timeFormatted: '17:25:00',
    source: 'SDRF Uttarakhand Rapid Force',
    action: 'Guide ropes installed. Controlled pedestrian passage only.',
  },
];
